### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yinpeng633** [CkNoSFeRaTU/android-ffmpegwrapper#1]
I want to build your this project to publish RTMP Stream to our server after reading this [https://github.com/Kickflip/kickflip-android-sdk/issues/30], but got the following error.
`building ffmpegwrapper-arm64-v8a...
Android NDK: ERROR:/home/yin/code/android-ffmpegwrapper/jni/Android.mk:avcodec: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/yin/code/android-ffmpegwrapper/jni/android/armeabi-v7a/lib/libavcodec-56.so exists  or that its path is correct   
/home/yin/android-ndk-r12b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    。`

Would you mind letting me know more details about how to build this project?

**Comment by CkNoSFeRaTU** [comment]
You need to edit NDK path in build.sh script in jni directory and run it afterward. It will build ffmpeg+ffmpegwrapper libraries for armv7, arm64 and x86.
